### ISSUE TITLE
[Flutter] change App name, icon

### ISSUE THREAD

**Issue by mic050r** [MuDuk-Club/tj-musical-number-book-app#11]
> Flutter, Android Studio 
### Change App Icon
`pubspec.yaml` 수정

```
dev_dependencies:
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png" # 아이콘 이미지 경로
```

```bash
flutter pub get
dart run flutter_launcher_icons
```

- Reference : https://pub.dev/packages/flutter_launcher_icons

### Change App Name
AndroidManifest.xml 수정
`android/app/src/main/AndroidManifest.xml` 파일을 열고, <application> 태그 내 android:label 속성 변경

```xml
<application
    android:label="새 앱 이름"
    ... >
```
