### ISSUE TITLE
[Flutter] 이미지 추가 방법

### ISSUE THREAD

**Issue by mic050r** [MuDuk-Club/tj-musical-number-book-app#6]
1. **이미지 파일 프로젝트에 추가하기**
  이미지 파일을 `assets` 폴더에 추가

   예시 경로
   ```
   /project-name/assets/img.png
   ```

2. **`pubspec.yaml` 파일 업데이트**

   이미지를 Flutter 프로젝트에서 사용할 수 있도록 `pubspec.yaml` 파일에 이미지 등록 필요
   `pubspec.yaml` 수정

   ```yaml
   flutter:
     assets:
       - assets/images/img.png
   ```

   여러 이미지를 같은 폴더에서 사용하고자 하면, 폴더 전체를 지정 가능 

   ```yaml
   flutter:
     assets:
       - assets/
   ```

3. **`flutter pub get` 실행**
  `pubspec.yaml` 파일을 업데이트한 후, 아래 명령어를 실행하여 프로젝트에 반영

   ```
   flutter pub get
   ```

4. **이미지 사용**

   ```dart
   Image.asset('assets/img.png')
   ```

![Image](https://github.com/user-attachments/assets/98bbb38b-4e92-4d65-8061-7ecc15e3a445)
